### PR TITLE
updated book and renamed inventory

### PR DESCRIPTION
**Pull request by Sabin-Pla**

### CODE REVIEW

**Comment by Sabin-Pla** [comment]
Need to have a better way to store cover before merging

**Comment by mfurqan26** [comment]
The reason we had an inventory class before is because each bookstore owner will have their own separate collection of books. Without having that, it might be tricky managing multiple book repositories for multiple store owners.

**Comment by Sabin-Pla** [comment]
> The reason we had an inventory class before is because each bookstore owner will have their own separate collection of books. Without having that, it might be tricky managing multiple book repositories for multiple store owners.

You are correct, we do need to keep track of which suppliers supply which products. I was thinking we can either have a `soldBy` property in Book, or we can have a BookId -> TupleOfTwoElements<Supplier, Integer (amount in stock)> within the BookRepository/Inventory class.

The motivation for preferring the latter option (as oppose to having multiple Inventory objects with their own book list) is that it becomes easier to query for some book when all books are part of the same attribute.

If you have all the books in different inventories, then any time you perform a query you have to join all of the lists of books together.

**Review by mfurqan26 — APPROVED** [review]
Good job

**Pull request merged**
